---
title: Goshen Scout Reservation
exclude: ["node_modules", "_styles", "gulpfile.js", "package.json",".vscode"]
collections:
  camps:
    output: true
  programs:
    output: true
  information:
    output: true
  events:
    output: true
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/Hero_Home.jpg"
      aboutImage: "/assets/G5001.jpg"
      tagline: "Learn Cool Stuff!"
      theme: "basic"
gmapKey: "AIzaSyBWuqMbXPRkZ85xMcsfDKIw-UrgVj0PbUM"